### ISSUE TITLE
实例分割效果的问题

### ISSUE THREAD

**Issue by zhDai** [zonasw/unet-nested-multiple-classification#5]
这位大哥，我在用你框架的时候，用的是9类的（算上背景）分割，效果感觉很糟，是不是我数据太少了，才400张左右==

**Comment by wangfusheng-cqu** [comment]
你这个代码可以跑通吗？？？我的数据集长宽尺寸不一样，会报错，RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 288 and 256 in dimension 3 at /opt/cond570711556059/work/aten/src/TH/generic/THTensor.cpp:689

**Comment by zhDai** [comment]
可以的~~不同长宽比也可以跑出不错的结果的，只要是16的倍数

**Comment by wangfusheng-cqu** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zonasw/unet-nested-multiple-classification"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 上午9:39
收件人:&nbsp;"zonasw/unet-nested-multiple-classification"<unet-nested-multiple-classification@noreply.github.com&gt;;
抄送:&nbsp;"咸鱼野鹤"<652317513@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [zonasw/unet-nested-multiple-classification] 实例分割效果的问题 (#5)





 
可以的~~不同长宽比也可以跑出不错的结果的，只要是16的倍数

**Comment by wangfusheng-cqu** [comment]
> 可以的~~不同长宽比也可以跑出不错的结果的，只要是16的倍数
你好！可以交流一下吗？？我QQ652317513

**Comment by zhDai** [comment]
> > 可以的~~不同长宽比也可以跑出不错的结果的，只要是16的倍数
> > 你好！可以交流一下吗？？我QQ652317513
没有qq，谢谢
